### ISSUE TITLE
npm install npm err! Error: failed to fetch from registry: gulp-autoprefixer

### ISSUE THREAD

**Issue by claenjoy** [toddmotto/html5blank#149]
on ubuntu 12.04.05 LTS

I got this error after the command npm install:

pm http GET https://registry.npmjs.org/del
npm http GET https://registry.npmjs.org/gulp
npm http GET https://registry.npmjs.org/gulp-autoprefixer
npm http GET https://registry.npmjs.org/gulp-concat
npm http GET https://registry.npmjs.org/gulp-csso
npm http GET https://registry.npmjs.org/gulp-jshint
npm http GET https://registry.npmjs.org/gulp-livereload
npm http GET https://registry.npmjs.org/gulp-load-plugins
npm http GET https://registry.npmjs.org/gulp-ruby-sass
npm http GET https://registry.npmjs.org/gulp-template
npm http GET https://registry.npmjs.org/gulp-uglify
npm http GET https://registry.npmjs.org/jshint-stylish

npm ERR! Error: failed to fetch from registry: gulp-autoprefixer
npm ERR!     at /usr/share/npm/lib/utils/npm-registry-client/get.js:139:12
npm ERR!     at cb (/usr/share/npm/lib/utils/npm-registry-client/request.js:31:9)
npm ERR!     at Request._callback (/usr/share/npm/lib/utils/npm-registry-client/request.js:136:18)
npm ERR!     at Request.callback (/usr/lib/nodejs/request/main.js:119:22)
npm ERR!     at Request.<anonymous> (/usr/lib/nodejs/request/main.js:212:58)
npm ERR!     at Request.emit (events.js:88:20)
npm ERR!     at ClientRequest.<anonymous> (/usr/lib/nodejs/request/main.js:412:12)
npm ERR!     at ClientRequest.emit (events.js:67:17)
npm ERR!     at HTTPParser.onIncoming (http.js:1261:11)
npm ERR!     at HTTPParser.onHeadersComplete (http.js:102:31)
npm ERR! You may report this log at:
npm ERR!     <http://bugs.debian.org/npm>
npm ERR! or use
npm ERR!     reportbug --attach /var/www/support/wp-content/themes/html5blank/npm-debug.log npm
npm ERR! 
npm ERR! System Linux 3.13.0-85-generic
npm ERR! command "node" "/usr/bin/npm" "install"
npm ERR! cwd /var/www/support/wp-content/themes/html5blank
npm ERR! node -v v0.6.12
npm ERR! npm -v 1.1.4
npm ERR! message failed to fetch from registry: gulp-autoprefixer
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /var/www/support/wp-content/themes/html5blank/npm-debug.log
npm not ok

**Comment by claenjoy** [comment]
fixed with the first solution 
http://stackoverflow.com/questions/12913141/message-failed-to-fetch-from-registry-while-trying-to-install-any-module
